[[KaHyPar]]
arch = "x86_64"
git-tree-sha1 = "839361bcfc9430c57b56f0bad0577fe198831dae"
os = "macos"

    [[KaHyPar.download]]
    sha256 = "552229fe5596ff4cacb8327f955aaf3fa0fa992f964adbefb1afefecdf74cb17"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.2.1+0/KaHyPar.v1.2.1.x86_64-apple-darwin.tar.gz"
[[KaHyPar]]
arch = "x86_64"
git-tree-sha1 = "1f9c17d74a12ed0de413318dd1f11e2379e4716f"
libc = "glibc"
os = "linux"

    [[KaHyPar.download]]
    sha256 = "9731ae724c02584acc403d71455b63d5ecb33a96d7a48c0174193f3e115cdf93"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.2.1+0/KaHyPar.v1.2.1.x86_64-linux-gnu.tar.gz"
[[KaHyPar]]
arch = "x86_64"
git-tree-sha1 = "41a2b67f7f02163d5385736f930bae663614f428"
libc = "musl"
os = "linux"

    [[KaHyPar.download]]
    sha256 = "1bf0e078f53c4c82697f7549f91b7e496c54d6a468cc0a6d9342b903cea8f7f9"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.2.1+0/KaHyPar.v1.2.1.x86_64-linux-musl.tar.gz"
[[KaHyPar]]
arch = "x86_64"
git-tree-sha1 = "459e64711e1a4e2ddde0f1bcdc665ef93a48c12e"
os = "freebsd"

    [[KaHyPar.download]]
    sha256 = "92cbfc19069a8416f897e2aa66a457ef47b755ecc614f58d99ee5fbd64d2b92b"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.2.1+0/KaHyPar.v1.2.1.x86_64-unknown-freebsd.tar.gz"
