[[KaHyPar]]
arch = "aarch64"
git-tree-sha1 = "37e07c19b7799a7642ef902b8800514d55bf0b5a"
os = "macos"

    [[KaHyPar.download]]
    sha256 = "a55db5d40af391e40ca88d82839bde394012147f3741b040330d5c6d0b5ed32a"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.3.5+0/KaHyPar.v1.3.5.aarch64-apple-darwin.tar.gz"
[[KaHyPar]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8152d2f9ceb15c16694974824acc741ca15e155"
libc = "glibc"
os = "linux"

    [[KaHyPar.download]]
    sha256 = "ccef4f36534198c78bc2a50fbce068fcaf012edca87b115f9ddc4677dac04877"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.3.5+0/KaHyPar.v1.3.5.aarch64-linux-gnu-cxx03.tar.gz"
[[KaHyPar]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "899beab3327670496d091a4efc2a129f6fc63f5d"
libc = "glibc"
os = "linux"

    [[KaHyPar.download]]
    sha256 = "dbe9df5f5c12bc7196f6710924d78c9c2435276534364cc676e8b737790b1c33"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.3.5+0/KaHyPar.v1.3.5.aarch64-linux-gnu-cxx11.tar.gz"
[[KaHyPar]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab878502c971c0d077a46d55edcc8f338770e3d0"
libc = "musl"
os = "linux"

    [[KaHyPar.download]]
    sha256 = "c2fa7aa26822c10205d994160613ba949e031c6c719a911849b3f7522e08c75b"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.3.5+0/KaHyPar.v1.3.5.aarch64-linux-musl-cxx03.tar.gz"
[[KaHyPar]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "905eab8715b767b13763c0acd020c681849e69da"
libc = "musl"
os = "linux"

    [[KaHyPar.download]]
    sha256 = "1fa65da8ae1224b8697ba84ab74e6dbc6c8f8547e1756ba521f14b9c6d3d7696"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.3.5+0/KaHyPar.v1.3.5.aarch64-linux-musl-cxx11.tar.gz"
[[KaHyPar]]
arch = "x86_64"
git-tree-sha1 = "4c0c4082b795c0e6366f1e8ea7d524b6f055edb0"
os = "macos"

    [[KaHyPar.download]]
    sha256 = "ca5da471ef3434c8744c7c6896b4ece0629ac46f70d94fcd4cbea0acd5eb3441"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.3.5+0/KaHyPar.v1.3.5.x86_64-apple-darwin.tar.gz"
[[KaHyPar]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "846e3f634ae2c651366950b894f48c1525cb1676"
libc = "glibc"
os = "linux"

    [[KaHyPar.download]]
    sha256 = "61a84df7aafa79b6fc3180eca506b2a3911d8484fff984eac417e7e960abb2b4"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.3.5+0/KaHyPar.v1.3.5.x86_64-linux-gnu-cxx03.tar.gz"
[[KaHyPar]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18a183e6bd4c7ae106fac1a7e4688843d9775c51"
libc = "glibc"
os = "linux"

    [[KaHyPar.download]]
    sha256 = "94c9cf2af6d0fff2412813c79b830eda2bb9672e78787363f1cd735478daa8b3"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.3.5+0/KaHyPar.v1.3.5.x86_64-linux-gnu-cxx11.tar.gz"
[[KaHyPar]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2f2e62ffa81f5af671afd9f8047bd7b8ce6eff5"
libc = "musl"
os = "linux"

    [[KaHyPar.download]]
    sha256 = "1fd8458e1a4fac7ffa62b46957a032bb81603328a131c3c29af77299c72f0bfd"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.3.5+0/KaHyPar.v1.3.5.x86_64-linux-musl-cxx03.tar.gz"
[[KaHyPar]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10e313c65a502bd3f6c8aa26d7ee04526909605b"
libc = "musl"
os = "linux"

    [[KaHyPar.download]]
    sha256 = "2110aef56c585a13c4560b8477421120bce387a22937e3de9043762e805b9dae"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.3.5+0/KaHyPar.v1.3.5.x86_64-linux-musl-cxx11.tar.gz"
[[KaHyPar]]
arch = "x86_64"
git-tree-sha1 = "cfe7e94f4fd6ed81f6fc0974d7f1d7ae03b20a1b"
os = "freebsd"

    [[KaHyPar.download]]
    sha256 = "2e04b292deace5988cef1943cfb6d906e7ed7a356f5a306c6e10abcde24fdde5"
    url = "https://github.com/JuliaBinaryWrappers/KaHyPar_jll.jl/releases/download/KaHyPar-v1.3.5+0/KaHyPar.v1.3.5.x86_64-unknown-freebsd.tar.gz"
